### ISSUE TITLE
Assignment

### ISSUE THREAD

**Issue by abhi280302** [LetsUpgrade/Cyber-Security-Essentials#1]
Where are the assignment???

**Comment by saurabhjangid2000** [comment]
Ya !!!  I sent a mail regarding this issue too ....
Assignments are not here on GitHub...

**Comment by AmandeepSingh13** [comment]
Was their any assignment I had to submit.

**Comment by shahidhannure** [comment]
Didn't find assignments

**Comment by naitikshah20** [comment]
Tomorrow upload assignment

**Comment by AmandeepSingh13** [comment]
Which Assignment i have to submit? Binayak Sir has given us no assignment,He will give it in the next class

**Comment by psbcg433** [comment]
I guess the assignment was  **Create 3 different subnets and connect them via same switch and see that they do not connect to each other**  .....this question is mentioned at 2:16:11 in the youtube video of Day 2....Binayak sir has asked to send screenshots of our  assignment..i think

**Comment by AmandeepSingh13** [comment]
Alright I will send it surely

**Comment by Allu-Philip** [comment]
But Sir told us to it as a classwork and save the file.Itz not a assignment

**Comment by abhi280302** [comment]
Yes ,it was just a classwork ,and it is clearly mentioned in the
description part of video that there is no assignment for today.

On 19 Aug 2020 17:05, "Allu_Philip" <notifications@github.com> wrote:

But Sir told us to it as a classwork and save the file.Itz not a assignment

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/LetsUpgrade/Cyber-Security-Essentials/issues/1#issuecomment-676196427>,
or unsubscribe
